### ISSUE TITLE
Production Go live Todo

### ISSUE THREAD

**Issue by nanorepublica** [djangosocialteam/djangosocial#26]
Starting this issue to get a list of items that need to be done so we can have a functioning site! 

In no particular order

* [x] Create production server
* [x] Deploy code to production server
* [x] Assign django.social DNS to production
* [x] Add initial content to the site
     * [x] Home Page
     * [ ] About Page?
     * [ ] Update any code that's missing for this to work
* [ ] Add links to header & footer
* [ ] Add & configure sentry
* [x] Decide on the DB we want to use (sqlite vs postgres)
